# For all values refer to 'helm_charts/SEMR/values.yaml'
# Change <CHANGE-ME> to IP of machine running the k8s cluster
general:
  ip: "<CHANGE-ME>"

# Ray
# Ray can't be disabled currently
rayVersion: "2.35.0"
headGroupSpecs:
  rayHead:
    resources:
      limits:
        cpu: "2"
        memory: "6G"
      requests:
        cpu: "2"
        memory: "6G"

# At least two ray workers required for distributed training
workerGroups:
  amdGroup:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    rayStartParams:
      numCpus: "2"
    container:
      resources:
        limits:
          cpu: "2"
          memory: "4G"
        requests:
          cpu: "2"
          memory: "4G"

# MLflow
mlflow:
  enabled: true

# MinIO
# MinIO is required by Flyte and Mlflow
minio:
  enabled: true
  # changing credentials will require fixes in other components and workflow examples!
  auth:
    rootUser: "minio"
    rootPassword: "miniostorage"

# Flyte
flyte-binary:
  enabled: true
  configuration:
    storage:
      providerConfig:
        s3:
          endpoint: "http://<CHANGE-ME>:30085"
    inline:
      plugins:
        k8s:
          default-env-vars:
            - FLYTE_AWS_ENDPOINT: "http://<CHANGE-ME>:30085"
            - FLYTE_AWS_ACCESS_KEY_ID: "minio"
            - FLYTE_AWS_SECRET_ACCESS_KEY: "miniostorage"


# promethes&grafana
kube-prometheus-stack:
  enabled: true
  grafana:
    grafana.ini:
      auth.anonymous:
        enabled: true
