# For all values refer to 'helm_charts/SEMR/values.yaml'

general:
  ip: "<CHANGE-ME>"

# Flyte
flyte-binary:
  configuration:
    storage:
      providerConfig:
        s3:
          endpoint: "http://<CHANGE-ME>:30085"
    inline:
      plugins:
        k8s:
          default-env-vars:
            - FLYTE_AWS_ENDPOINT: "http://<CHANGE-ME>:30085"


# Ray
headGroupSpecs:
  rayHead:
    resources:
      limits:
        cpu: "2"
        memory: "6G"
      requests:
        cpu: "2"
        memory: "6G"

workerGroups:
  amdGroup:
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    rayStartParams:
      numCpus: "2"
    container:
      resources:
        limits:
          cpu: "2"
          memory: "6G"
        requests:
          cpu: "2"
          memory: "6G"
