tracking:
  auth:
    enabled: false
minio:
  enabled: false

config:
externalS3:
  host: "minio.minio.svc.cluster.local"
  port: 9000
  accessKeyID: "minio"
  accessKeySecret: "miniostorage"
  protocol: "http"
  bucket: "mlflow"
  serveArtifacts: true
