tracking:
  auth:
    enabled: false
  service:
    type: NodePort
    ports:
      http: 80
    nodePorts:
      http: "31007"
  nodeSelector:
    kubernetes.io/arch: "amd64"

run:
  nodeSelector:
    kubernetes.io/arch: "amd64"

minio:
  enabled: false

config:
externalS3:
  host: "minio.minio.svc.cluster.local"
  port: 9000
  accessKeyID: "minio"
  accessKeySecret: "miniostorage"
  protocol: "http"
  bucket: "mlflow"
  serveArtifacts: true
