deployment:
  replicas: 3

container:
  image: copandrej/cnn-spectrum-endpoint-arm # Container image
  port: 8000
  env:
    - name: MODEL_VERSION
      value: "latest"
    - name: ENDPOINT
      value: "CNN"

nodeSelector:
  arch: arm64

service:
  targetPort: 8000 # equal to container port
  nodePort: 30070 # service endpoint
