deployment:
  replicas: 3

container:
  image: copandrej/nvg-endpoint-arm # Container image
  port: 8000
  env:
    - name: MODEL_VERSION
      value: "latest"
    - name: ENDPOINT
      value: "NVG"

nodeSelector:
  arch: arm64

service:
  type: NodePort
  port: 80         # Service port
  targetPort: 8000 # equal to container port
  nodePort: 30071 # service endpoint
