apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: prometheus-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: prometheus-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: prometheus-kube-prometheus-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002