apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: ray-serve
spec:
  # this is example serving config, here we need to put some placeholder text return serving
  serveConfigV2: |
    applications:
      - name: text_ml_app
        import_path: text_ml.app
        route_prefix: /summarize_translate
        runtime_env:
          working_dir: "https://github.com/ray-project/serve_config_examples/archive/36862c251615e258a58285934c7c41cffd1ee3b7.zip"
          pip:
            - torch
            - transformers
        deployments:
          - name: Translator
            num_replicas: 1
            ray_actor_options:
              num_cpus: 0.2
            user_config:
              language: french
          - name: Summarizer
            num_replicas: 1
            ray_actor_options:
              num_cpus: 0.2
  rayClusterConfig:
    rayVersion: '2.9.1' # Should match the Ray version in the image of the containers
    #############auto scaler copied from https://github.com/ray-project/kuberay/blob/5b1a5a11f5df76db2d66ed332ff0802dc3bbff76/ray-operator/config/samples/ray-cluster.autoscaler.yaml ############################
    enableInTreeAutoscaling: true
    # `autoscalerOptions` is an OPTIONAL field specifying configuration overrides for the Ray Autoscaler.
    # The example configuration shown below below represents the DEFAULT values.
    # (You may delete autoscalerOptions if the defaults are suitable.)
    autoscalerOptions:
      # `upscalingMode` is "Default" or "Aggressive."
      # Conservative: Upscaling is rate-limited; the number of pending worker pods is at most the size of the Ray cluster.
      # Default: Upscaling is not rate-limited.
      # Aggressive: An alias for Default; upscaling is not rate-limited.
      upscalingMode: Default
      # `idleTimeoutSeconds` is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
      idleTimeoutSeconds: 30
      # `image` optionally overrides the Autoscaler's container image. The Autoscaler uses the same image as the Ray container by default.
      ## image: "my-repo/my-custom-autoscaler-image:tag"
      # `imagePullPolicy` optionally overrides the Autoscaler container's default image pull policy (IfNotPresent).
      imagePullPolicy: IfNotPresent
      # Optionally specify the Autoscaler container's securityContext.
      securityContext: { }
      env: [ ]
      envFrom: [ ]
      # resources specifies optional resource request and limit overrides for the Autoscaler container.
      # The default Autoscaler resource limits and requests should be sufficient for production use-cases.
      # However, for large Ray clusters, we recommend monitoring container resource usage to determine if overriding the defaults is required.
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "500m"
          memory: "512Mi"

    ######################headGroupSpecs#################################
    # Ray head pod template.
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: "0" # we don't want training and serving to get scheduled on head
      # Pod template
      template:
        spec:
          containers:
          - name: ray-head
            image: copandrej/ijs-custom:ray-amd64-ray29
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            volumeMounts:
              - mountPath: /tmp/ray
                name: ray-logs
            resources:
              limits:
                cpu: "1"
                memory: "8G"
              requests:
                cpu: "1"
                memory: "8G"
          volumes:
            - name: ray-logs
              emptyDir: {}
          nodeSelector:
            kubernetes.io/arch: "amd64"
    workerGroupSpecs:
    # The pod replicas in this group typed worker
    - replicas: 1
      minReplicas: 1
      maxReplicas: 1
      groupName: amd-group
      rayStartParams:
        num-cpus: "4"
      # Pod template
      template:
        spec:
          containers:
          - name: ray-worker
            image: copandrej/ijs-custom:ray-amd64-ray29
            resources:
              limits:
                cpu: 4
                memory: "6G"
              requests:
                cpu: 4
                memory: "6G"
          nodeSelector:
            kubernetes.io/arch: "amd64"
    # maxReplicas should equal to the number of raspberry pi 5 nodes
    - replicas: 3
      minReplicas: 3
      maxReplicas: 3
      groupName: aarch-group
      rayStartParams:
        num-cpus: "4"
      # Pod template
      template:
        spec:
          containers:
          - name: ray-worker
            image: copandrej/ijs-custom:ray-aarch64-ray29
            resources:
              limits:
                cpu: "3.75"
                memory: "5G"
              requests:
                cpu: "3.75"
                memory: "5G"
          nodeSelector:
            kubernetes.io/arch: "arm64"
