apiVersion: v1
kind: Service
metadata:
  name: ray-serve-head-svc-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/created-by: kuberay-operator
    app.kubernetes.io/name: kuberay
    ray.io/node-type: head
  ports:
    - name: client 
      protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30001
    - name: dashboard
      protocol: TCP
      port: 8265
      targetPort: 8265
      nodePort: 30265
    - name: serve
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ip
data:
  #  get ip from values, these are helm chart templates
  GRAFANA_IP: "http://{{ .Values.general.ip }}:30000"