# worker-nodeport.yaml

{{- if .Values.workerGroups.amdGroup.container.ports }}
apiVersion: v1
kind: Service
metadata:
  name: amd-group-nodeport
spec:
  type: NodePort
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  selector:
    ray.io/group: amd-group
  ports:
    {{- range $index, $port := .Values.workerGroups.amdGroup.container.ports }}
    - protocol: TCP
      port: {{ $port }}
      targetPort: {{ $port }}
      nodePort: {{ index $.Values.workerGroups.amdGroup.container.nodePorts $index }}
      name: port-{{ $index }}
    {{- end }}
{{- end }}

---
{{- if .Values.workerGroups.aarchGroup.container.ports }}
apiVersion: v1
kind: Service
metadata:
  name: aarch-group-nodeport
spec:
  type: NodePort
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  selector:
    ray.io/group: aarch-group
  ports:
    {{- range $index, $port := .Values.workerGroups.aarchGroup.container.ports }}
    - protocol: TCP
      port: {{ $port }}
      targetPort: {{ $port }}
      nodePort: {{ index $.Values.workerGroups.aarchGroup.container.nodePorts $index }}
      name: port-{{ $index }}
    {{- end }}
{{- end }}