apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-endpoint
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-endpoint
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: {{ .Values.container.image }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
          {{- toYaml .Values.container.env | nindent 10 }}
      nodeSelector:
        kubernetes.io/arch: {{ .Values.nodeSelector.arch }}

