apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator-crds
spec:
  project: default
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision: v1.0.0-rc.0
    path: helm-chart/kuberay-operator/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: ray-system
  syncPolicy:
    syncOptions:
    - Replace=true
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator
spec:
  project: default
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision: v1.0.0-rc.0
    path: helm-chart/kuberay-operator
    helm:
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ray-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray
spec:
  project: default
  source:
    repoURL: 'https://github.com/copandrej/IJS-AI_orchestration.git'
    path: conf/kube_conf/ray
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ray-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flyte-binary
spec:
  project: default
  sources:
    - repoURL: 'https://flyteorg.github.io/flyte'
      chart: flyte-binary
      targetRevision: 1.10.6
      helm:
        valueFiles:
          - $values/conf/kube_conf/flyte/values/local-values.yaml
    - repoURL: 'https://github.com/copandrej/IJS-AI_orchestration.git'
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: flyte
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flyte-resources
spec:
  project: default
  source:
    repoURL: 'https://github.com/copandrej/IJS-AI_orchestration.git'
    path: conf/kube_conf/flyte
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flyte
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  source:
    repoURL: 'https://github.com/copandrej/IJS-AI_orchestration.git'
    path: conf/kube_conf/minio
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
