apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-head-monitor
  labels:
    release: {{ .Release.Name }}
spec:
  jobLabel: ray-head
  selector:
    matchLabels:
      ray.io/node-type: head
  endpoints:
    - port: metrics
  targetLabels:
  - ray.io/cluster
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-workers-monitor
  labels:
    release: {{ .Release.Name }}
    ray.io/cluster: ray-serve-raycluster
spec:
  jobLabel: ray-workers
  selector:
    matchLabels:
      ray.io/node-type: worker
  podMetricsEndpoints:
  - port: metrics