apiVersion: v2
name: NAOMI
description: NAOMI Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "0.2.0"

dependencies:
- condition: mlflow.enabled
  name: mlflow
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 1.5.0

- condition: minio.enabled
  name: minio
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.7.7

- condition: flyte-binary.enabled
  name: flyte-binary
  repository: https://flyteorg.github.io/flyte
  version: 1.13.1

- name: kuberay-operator
  repository: https://ray-project.github.io/kuberay-helm/
  version: 1.0.0-rc.0

- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 62.6.0
